# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='', verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
                'db_table': 'Picture',
            },
        ),
        migrations.CreateModel(
            name='Picture_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'picture_type',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Picture_Type'),
        ),
    ]
